### ISSUE TITLE
audio_demo.py normalized_dir, noise_aggressiveness typos? and torchvision problems

### ISSUE THREAD

**Issue by nanonomad** [rioharper/VocalForge#6]
Hi,
Was going to take another look at this project but having a couple probably minor issues:

(VocalForge) nano@DESKTOP-73RPGPM:~/VocalForge$ python audio_demo.py --raw_dir /mnt/d/abtest --work_dir /mnt/d/abtest-workdir
CUDA device configured correctly!
Traceback (most recent call last):
  File "audio_demo.py", line 52, in <module>
    Refine_Audio = RefineAudio(
TypeError: __init__() got an unexpected keyword argument 'normalized_dir'

Found refine_audio.py
Line 61:            normalization_dir=self.Normalized_Dir,
Edited audio_demo.py to change normalized_dir to normalization_dir

Then ran into this:
(VocalForge) nano@DESKTOP-73RPGPM:~/VocalForge$ python audio_demo.py --raw_dir /mnt/d/abtest --work_dir /mnt/d/abtest-workdir
CUDA device configured correctly!
Traceback (most recent call last):
  File "audio_demo.py", line 52, in <module>
    Refine_Audio = RefineAudio(
TypeError: __init__() got an unexpected keyword argument 'noise_aggressiveness'

Edited audio_demo.py again, line 63:
    noise_aggressiveness=args.snr_change,
changed to 
    snr_change=args.snr_change,

Now it launches. Not sure if I made the correct changes; I'm a cook not a coder.

Now I get this:
(VocalForge) nano@DESKTOP-73RPGPM:~/VocalForge$ python audio_demo.py --raw_dir /mnt/d/abtest --work_dir /mnt/d/abtest-workdir
CUDA device configured correctly!
/home/nano/anaconda3/envs/VocalForge/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/nano/anaconda3/envs/VocalForge/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
  warn(f"Failed to load image Python extension: {e}")
Segmentation fault
(VocalForge) nano@DESKTOP-73RPGPM:~/VocalForge$

I think the requirements.txt is installing torch without torchvision. Going to go reinstall my env and see if I can resolve this later tonight.

Updated to torch 2 and torchaudio 2.0.1, now it launches to this point:

(VocalForge) nano@DESKTOP-73RPGPM:~/VocalForge$ python audio_demo.py --raw_dir /mnt/d/abtest --work_dir /mnt/d/abtest-workdir
CUDA device configured correctly!
Downloading pytorch_model.bin: 100%|███████████████████████████████████████████████| 96.4M/96.4M [00:07<00:00, 12.3MB/s]
Downloading (…)lve/main/config.yaml: 100%|██████████████████████████████████████████| 2.00k/2.00k [00:00<00:00, 510kB/s]
Traceback (most recent call last):
  File "audio_demo.py", line 65, in <module>
    Refine_Audio.run_all()
  File "/home/nano/VocalForge/audio/refine_audio.py", line 66, in run_all
    self.VoiceDetection.run_vad()
  File "/home/nano/VocalForge/audio/voice_detection.py", line 135, in run_vad
    self.find_timestamps()
  File "/home/nano/VocalForge/audio/voice_detection.py", line 76, in find_timestamps
    elif c50_med * self.SNR_Change > c50 and startpoint == False:
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

..and I'm stumped.  Any help would be appreciated.

**Comment by rioharper** [comment]
Hello! Sorry for all your issues.

I fixed the problem with torch. Apparently, the torch version installed with pip overrided the version installed with the conda enviroment, so I removed it off the requirements.txt and it no longer brings up that issue. I dont know why it became an issue now, as it wasnt causing as issue a few weeks ago, but thats libraries for you, I guess!

As for your last issue, I didnt run into that problem. It could because pyannote failed to analyze the audio clip(s) that is in your raw_dir directory. Im not sure how pyannote plays with torch 2.0, so if you wouldnt mind reinstalling the environment with the new requirements.txt and to ensure that the audio in the raw_dir isnt corrupted/is in another format other than wav and report back as to if it works, that would be great!

If that doesn't solve your issue, I'd be happy to look into it further. I'm thinking of changing the demo to be in notebook format, so these kind of issues are easier to dissect, but I want to see if I can fix your issue first.

Cheers,
Rio
